// COMMON
export const HOME_SCREEN = "HOME_SCREEN";
export const PRODUCTS_SCREEN = "PRODUCTS_SCREEN";
export const HELP_SCREEN = "HELP_SCREEN";
export const NO_CONNECTION = "NO_CONNECTION";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const RESET_PIN = "RESET_PIN";
export const SECURITY_SETTINGS = "SECURITY_SETTINGS";
export const PASSWORD_RECOVER_CODE = "PASSWORD_RECOVER_CODE";
export const SECURITY_ANSWER = "SECURITY_ANSWER";
